language: php

# See https://travis-ci.community/t/php-5-4-and-5-5-archives-missing/3723
dist: trusty

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - travis_retry composer install --no-interaction --prefer-dist

script: make test
