language: php

sudo: false

matrix:
  include:
    # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
    - php: hhvm-3.12
      sudo: required
      dist: trusty
      group: edge
    - php: 5.6
    - php: 7.0
    - php: 7.1
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction --prefer-dist

script: make test
